### ISSUE TITLE
Create sample neo4j queries which will yield statistics for use by the backend/frontend

### ISSUE THREAD

**Issue by smspillaz** [smspillaz/pubmed-retraction-analysis#12]
**Problem:**\* We need to create some neo4j queries which will return some useful statistics, for instance the following:
- [x] Retractions by X by Y (bar chart, discrete data)
- [x] Retractions over time for X
- [x] Retractions breakdown by X (mutually exclusive data)

**Blocked on** Getting the data in #14

**Comment by smspillaz** [comment]
@jknlsn any progress on this?

**Comment by jknlsn** [comment]
No been totally taken up with study for AI, will be done by end of week.

**Comment by smspillaz** [comment]
@jknlsn are these stored somewhere?

**Comment by jknlsn** [comment]
Please see f6263ed0011f3023078db233539b7b13f905577f
